name: Build Linux App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'beta'
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Install dependencies
      run: flutter pub get

    - name: Build Linux executable
      run: flutter build linux

    - name: Upload Linux executable
      uses: actions/upload-artifact@v4
      with:
        name: linux-app
        path: build/linux/x64/release/bundle/
